nginx:
    build: ./nginx
    links:
        - node1:node1
    ports:
        - "80:80"
node1:
    build: ./node
    volumes:
        - /Users/mpierce/www/59023c/node:/src
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"
