export const FETCH_USER = 'FETCH_USER'
export const FETCH_POSTS = 'FETCH_USER_POSTS'

export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS_SUCCESS = 'RECEIVE_POSTS_SUCCESS'
export const RECEIVE_POSTS_FAILURE = 'RECEIVE_POSTS_FAILURE'

export const REQUEST_POST = 'REQUEST_POST'
export const RECEIVE_POST_SUCCESS = 'RECEIVE_POST_SUCCESS'
export const RECEIVE_POST_FAILURE = 'RECEIVE_POST_FAILURE'


export const SELECTED_POST = 'SELECTED_POST'



export const LOCALE_SWITCHED = 'LOCALE_SWITCHED'

export const ADD_POST = 'ADD_POST'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE'

export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const RECEIVE_LOGIN_SUCCESS = 'RECEIVE_LOGIN_SUCCESS'
export const RECEIVE_LOGIN_FAILURE = 'RECEIVE_LOGIN_FAILURE'

export const LOG_OUT = 'LOG_OUT'

export const SHOW_ERROR = 'SHOW_ERROR'
export const HIDE_ERROR = 'HIDE_ERROR'

// export const FETCH_REPO = 'FETCH_REPO'
// export const FETCH_USER_STARGAZERS = 'FETCH_USER_STARGAZERS'
// export const FETCH_REPO_STARGAZERS = 'FETCH_REPO_STARGAZERS'
// export const FETCH_USER_STARGAZERS = 'FETCH_USER_STARGAZERS'
// export const FETCH_REPO_STARGAZERS = 'FETCH_REPO_STARGAZERS'
