# Base image
FROM debian:jessie

MAINTAINER Michael Pierce <hi@mep.im>

# Update the repository and install Redis Server
RUN apt-get update && apt-get install -y wget make sed gcc



RUN \
  cd /tmp && \
  wget http://download.redis.io/redis-stable.tar.gz && \
  tar xvzf redis-stable.tar.gz && \
  cd redis-stable && \
  make && \
  make install && \
  cp -f src/redis-sentinel /usr/local/bin && \
  mkdir -p /etc/redis && \
  cp -f *.conf /etc/redis && \
  rm -rf /tmp/redis-server* && \
  sed -i 's/^\(bind .*\)$/# \1/' /etc/redis/redis.conf && \
  sed -i 's/^\(daemonize .*\)$/# \1/' /etc/redis/redis.conf && \
  sed -i 's/^\(dir .*\)$/# \1\ndir \/data/' /etc/redis/redis.conf && \
  sed -i 's/^\(logfile .*\)$/# \1/' /etc/redis/redis.conf

VOLUME ./data/:/data

WORKDIR /data
ADD . /data

CMD  ["redis-server", "--appendonly yes"]


# Expose Redis port 6379
EXPOSE 6379
